ui:
  port: ""
  image: icr.io/ai-services/catalog-ui:v0.0.46

backend:
  port: ""
  image: icr.io/ai-service/ai-services:v0.0.222
  runtime: ""
  adminPasswordHash: ""
  podman:
    uri: "/run/podman/podman.sock"
    authFileContent: ""

db:
  port: ""
  image: icr.io/ai-services/postgres:18-4
  user: "postgres"
  database: "ai_services"
  password: ""
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"

caddy:
  image: icr.io/ai-services/caddy:v2.11.4-1
  adminPort: ""
  httpsPort: ""
